version: "3.7"

networks:
  keycloak-network:
    driver: bridge

volumes:
  dbkeycloak:
    driver: local

services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_ADDR=${DB_ADDR}
      - DB_SCHEMA=${DB_SCHEMA}
    env_file:
      - .env
    links:
      - db:db
    ports:
    - 8081:8080
    networks:
      - keycloak-network

  db:
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - dbkeycloak:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - keycloak-network
    restart: unless-stopped